name       : cve-check-tool
version    : 5.6.4
release    : 18
source     :
    - git|git://git.altlinux.org/gears/c/cve-check-tool.git : 5.6.4-alt16.git.cbc2d0e
license    : GPL-2.0-or-later
component  : security
summary    : Vulnerability checker for Linux packaging
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs. The tool will identify potentially vulnerable software packages within Linux distributions through version matching. Where possible it will also seek to determine (through a distribution implementation) if a vulnerability has been addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(jansson)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - libt1ha
setup      : |
    # Causes segfaults with our current mapping
    %patch -p1 < $pkgfiles/0001-Revert-version-mapping-support.patch
    # Upstream changes require release to be a string now but they borked it for eopkg. Needs looking at further.
    %patch -p1 < $pkgfiles/0002-Point-release-to-tmp-pointer-and-get-rid-of-release_.patch
    # Unsure if we want to commit to smhasher yet...
    %patch -p1 < $pkgfiles/0003-Use-sha1-instead-of-murmur-hash.patch

    # Don't compile for pkg managers we don't care about
    # and avoids having to package smhasher for now.
    sed -i '/faux/d' src/plugins/Makefile.am
    sed -i '/pkgbuild/d' src/plugins/Makefile.am
    sed -i '/rpm/d' src/plugins/Makefile.am

    %autogen
build      : |
    %make
install    : |
    %make_install
#check      : |
#    %make check
