name       : cve-check-tool
version    : 5.6
release    : 10
source     :
    - https://github.com/ikeydoherty/cve-check-tool/releases/download/v5.6/cve-check-tool-5.6.tar.xz : d35af2bfa014b9d7cdc9c59ec0bd7df40c22dfcd57244c9099c0aa9bdc9c0cb4
license    : GPL-2.0
summary    : Vulnerability checker for Linux packaging
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs.
    he tool will identify potentially vunlnerable software packages within Linux
    distributions through version matching. Where possible it will also seek to
    determine (through a distribution implemention) if a vulnerability has been
    addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
