name       : cve-check-tool
version    : 5.1
release    : 1
source     :
    - https://github.com/ikeydoherty/cve-check-tool/releases/download/v5.1/cve-check-tool-5.1.tar.xz : aceb60b9f1fbbeecd3d678c78139f19ad100d4e10c5f5a5cde2e66b6911a08fd
license    : GPL-2.0
summary    : Vulnerability checker for Linux packaging
 # Bad ikey, unused variables.
clang      : no
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs.
    he tool will identify potentially vunlnerable software packages within Linux
    distributions through version matching. Where possible it will also seek to
    determine (through a distribution implemention) if a vulnerability has been
    addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
