name       : cve-check-tool
version    : 5.6.4
release    : 13
source     :
    - https://github.com/ikeydoherty/cve-check-tool/releases/download/v5.6.4/cve-check-tool-5.6.4.tar.xz : b8f283be718af8d31232ac1bfc10a0378fb958aaaa49af39168f8acf501e6a5b
license    : GPL-2.0
summary    : Vulnerability checker for Linux packaging
component  : security
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs.
    he tool will identify potentially vunlnerable software packages within Linux
    distributions through version matching. Where possible it will also seek to
    determine (through a distribution implemention) if a vulnerability has been
    addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make check
