name       : cve-check-tool
version    : 5.6.4
release    : 16
source     :
    - git|https://github.com/clearlinux/cve-check-tool.git : cbc2d0e4fe56c5c82100c249badd8620fe2b22a2
license    : GPL-2.0-or-later
summary    : Vulnerability checker for Linux packaging
component  : security
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs. The tool will identify potentially vulnerable software packages within Linux distributions through version matching. Where possible it will also seek to determine (through a distribution implementation) if a vulnerability has been addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(jansson)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %patch -p1 < $pkgfiles/Migrate-to-JSON.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
