name       : cve-check-tool
version    : 5.6.3
release    : 11
source     :
    - https://github.com/ikeydoherty/cve-check-tool/releases/download/v5.6.3/cve-check-tool-5.6.3.tar.xz : 34f3ad1b0a0f94641d7da0f5460d960ea6dc15e1f112967c374e2d92422b6cc4
license    : GPL-2.0
summary    : Vulnerability checker for Linux packaging
description: |
    cve-check-tool, as its name suggests, is a tool for checking known (public) CVEs.
    he tool will identify potentially vunlnerable software packages within Linux
    distributions through version matching. Where possible it will also seek to
    determine (through a distribution implemention) if a vulnerability has been
    addressed by way of a patch.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gio-2.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
